---
title: "Afternoon Talk Session"
date: ""
output: 
  html_document:
    theme: sandstone
    toc: FALSE
    toc_float: FALSE
    css: style.css
editor_options: 
  chunk_output_type: console
---
<br>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:b="urn:schemas-microsoft-com:office:publisher"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List href="afternoonSession_files/filelist.xml">
<link rel=Edit-Time-Data href="afternoonSession_files/editdata.mso">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]--><!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>Alex Filazzola</o:Author>
  <o:Template>Normal</o:Template>
  <o:LastAuthor>Alex Filazzola</o:LastAuthor>
  <o:Revision>1</o:Revision>
  <o:TotalTime>1</o:TotalTime>
  <o:Created>2020-02-11T22:09:00Z</o:Created>
  <o:LastSaved>2020-02-11T22:10:00Z</o:LastSaved>
  <o:Pages>1</o:Pages>
  <o:Words>179</o:Words>
  <o:Characters>1023</o:Characters>
  <o:Lines>8</o:Lines>
  <o:Paragraphs>2</o:Paragraphs>
  <o:CharactersWithSpaces>1200</o:CharactersWithSpaces>
  <o:Version>16.00</o:Version>
 </o:DocumentProperties>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
<link rel=themeData href="afternoonSession_files/themedata.thmx">
<link rel=colorSchemeMapping
href="afternoonSession_files/colorschememapping.xml">
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:SpellingState>Clean</w:SpellingState>
  <w:GrammarState>Clean</w:GrammarState>
  <w:TrackMoves>false</w:TrackMoves>
  <w:TrackFormatting/>
  <w:PunctuationKerning/>
  <w:ValidateAgainstSchemas/>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:DoNotPromoteQF/>
  <w:LidThemeOther>EN-US</w:LidThemeOther>
  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>
  <w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>
  <w:Compatibility>
   <w:BreakWrappedTables/>
   <w:SnapToGridInCell/>
   <w:WrapTextWithPunct/>
   <w:UseAsianBreakRules/>
   <w:DontGrowAutofit/>
   <w:SplitPgBreakAndParaMark/>
   <w:EnableOpenTypeKerning/>
   <w:DontFlipMirrorIndents/>
   <w:OverrideTableStyleHps/>
  </w:Compatibility>
  <m:mathPr>
   <m:mathFont m:val="Cambria Math"/>
   <m:brkBin m:val="before"/>
   <m:brkBinSub m:val="&#45;-"/>
   <m:smallFrac m:val="off"/>
   <m:dispDef/>
   <m:lMargin m:val="0"/>
   <m:rMargin m:val="0"/>
   <m:defJc m:val="centerGroup"/>
   <m:wrapIndent m:val="1440"/>
   <m:intLim m:val="subSup"/>
   <m:naryLim m:val="undOvr"/>
  </m:mathPr></w:WordDocument>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="false"
  DefSemiHidden="false" DefQFormat="false" DefPriority="99"
  LatentStyleCount="377">
  <w:LsdException Locked="false" Priority="0" QFormat="true" Name="Normal"/>
  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 1"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 2"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 3"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 4"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 5"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 6"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 7"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 8"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 9"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 1"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 2"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 3"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 4"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 5"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 6"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 7"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 8"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="header"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footer"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index heading"/>
  <w:LsdException Locked="false" Priority="35" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="caption"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of figures"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope address"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope return"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="line number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="page number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of authorities"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="macro"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="toa heading"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number 5"/>
  <w:LsdException Locked="false" Priority="10" QFormat="true" Name="Title"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Closing"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Signature"/>
  <w:LsdException Locked="false" Priority="1" SemiHidden="true"
   UnhideWhenUsed="true" Name="Default Paragraph Font"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Continue 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Message Header"/>
  <w:LsdException Locked="false" Priority="11" QFormat="true" Name="Subtitle"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Salutation"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Date"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text First Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text First Indent 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Note Heading"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Body Text Indent 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Block Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Hyperlink"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="FollowedHyperlink"/>
  <w:LsdException Locked="false" Priority="22" QFormat="true" Name="Strong"/>
  <w:LsdException Locked="false" Priority="20" QFormat="true" Name="Emphasis"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Document Map"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Plain Text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="E-mail Signature"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Top of Form"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Bottom of Form"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal (Web)"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Acronym"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Address"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Cite"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Code"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Definition"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Keyboard"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Preformatted"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Sample"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Typewriter"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="HTML Variable"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation subject"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="No List"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Outline List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Simple 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Classic 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Colorful 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Columns 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Grid 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table List 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table 3D effects 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Contemporary"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Elegant"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Professional"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Subtle 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Subtle 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Web 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Table Web 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Balloon Text"/>
  <w:LsdException Locked="false" Priority="39" Name="Table Grid"/>
  <w:LsdException Locked="false" SemiHidden="true" Name="Placeholder Text"/>
  <w:LsdException Locked="false" Priority="1" QFormat="true" Name="No Spacing"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 1"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 1"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 1"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 1"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 1"/>
  <w:LsdException Locked="false" SemiHidden="true" Name="Revision"/>
  <w:LsdException Locked="false" Priority="34" QFormat="true"
   Name="List Paragraph"/>
  <w:LsdException Locked="false" Priority="29" QFormat="true" Name="Quote"/>
  <w:LsdException Locked="false" Priority="30" QFormat="true"
   Name="Intense Quote"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 1"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 1"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 1"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 1"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 1"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 2"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 2"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 2"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 2"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 2"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 2"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 2"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 2"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 3"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 3"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 3"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 3"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 3"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 3"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 3"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 3"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 4"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 4"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 4"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 4"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 4"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 4"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 4"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 4"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 5"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 5"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 5"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 5"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 5"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 5"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="60" Name="Light Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="61" Name="Light List Accent 6"/>
  <w:LsdException Locked="false" Priority="62" Name="Light Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="63" Name="Medium Shading 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="64" Name="Medium Shading 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="65" Name="Medium List 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="66" Name="Medium List 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="67" Name="Medium Grid 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="68" Name="Medium Grid 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="69" Name="Medium Grid 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="70" Name="Dark List Accent 6"/>
  <w:LsdException Locked="false" Priority="71" Name="Colorful Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="72" Name="Colorful List Accent 6"/>
  <w:LsdException Locked="false" Priority="73" Name="Colorful Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="19" QFormat="true"
   Name="Subtle Emphasis"/>
  <w:LsdException Locked="false" Priority="21" QFormat="true"
   Name="Intense Emphasis"/>
  <w:LsdException Locked="false" Priority="31" QFormat="true"
   Name="Subtle Reference"/>
  <w:LsdException Locked="false" Priority="32" QFormat="true"
   Name="Intense Reference"/>
  <w:LsdException Locked="false" Priority="33" QFormat="true" Name="Book Title"/>
  <w:LsdException Locked="false" Priority="37" SemiHidden="true"
   UnhideWhenUsed="true" Name="Bibliography"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="TOC Heading"/>
  <w:LsdException Locked="false" Priority="41" Name="Plain Table 1"/>
  <w:LsdException Locked="false" Priority="42" Name="Plain Table 2"/>
  <w:LsdException Locked="false" Priority="43" Name="Plain Table 3"/>
  <w:LsdException Locked="false" Priority="44" Name="Plain Table 4"/>
  <w:LsdException Locked="false" Priority="45" Name="Plain Table 5"/>
  <w:LsdException Locked="false" Priority="40" Name="Grid Table Light"/>
  <w:LsdException Locked="false" Priority="46" Name="Grid Table 1 Light"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark"/>
  <w:LsdException Locked="false" Priority="51" Name="Grid Table 6 Colorful"/>
  <w:LsdException Locked="false" Priority="52" Name="Grid Table 7 Colorful"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 1"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 1"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 1"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 2"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 2"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 2"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 3"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 3"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 3"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 4"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 4"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 4"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 5"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 5"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 5"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="46"
   Name="Grid Table 1 Light Accent 6"/>
  <w:LsdException Locked="false" Priority="47" Name="Grid Table 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="48" Name="Grid Table 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="49" Name="Grid Table 4 Accent 6"/>
  <w:LsdException Locked="false" Priority="50" Name="Grid Table 5 Dark Accent 6"/>
  <w:LsdException Locked="false" Priority="51"
   Name="Grid Table 6 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="52"
   Name="Grid Table 7 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="46" Name="List Table 1 Light"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark"/>
  <w:LsdException Locked="false" Priority="51" Name="List Table 6 Colorful"/>
  <w:LsdException Locked="false" Priority="52" Name="List Table 7 Colorful"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 1"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 1"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 1"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 1"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 1"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 1"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 2"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 2"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 2"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 2"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 2"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 2"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 3"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 3"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 3"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 3"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 3"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 3"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 4"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 4"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 4"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 4"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 4"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 4"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 5"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 5"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 5"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 5"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 5"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 5"/>
  <w:LsdException Locked="false" Priority="46"
   Name="List Table 1 Light Accent 6"/>
  <w:LsdException Locked="false" Priority="47" Name="List Table 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="48" Name="List Table 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="49" Name="List Table 4 Accent 6"/>
  <w:LsdException Locked="false" Priority="50" Name="List Table 5 Dark Accent 6"/>
  <w:LsdException Locked="false" Priority="51"
   Name="List Table 6 Colorful Accent 6"/>
  <w:LsdException Locked="false" Priority="52"
   Name="List Table 7 Colorful Accent 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Mention"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Smart Hyperlink"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Hashtag"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Unresolved Mention"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Smart Link"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Smart Link Error"/>
 </w:LatentStyles>
</xml><![endif]-->
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:3 0 0 0 1 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-469750017 -1073732485 9 0 511 0;}
@font-face
	{font-family:Verdana;
	panose-1:2 11 6 4 3 5 4 4 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-1610610945 1073750107 16 0 415 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:6.0pt;
	margin-left:0in;
	line-height:118%;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-font-family:"Times New Roman";
	color:black;
	mso-font-kerning:14.0pt;
	mso-ligatures:standard;
	mso-contextual-alternates:yes;}
span.SpellE
	{mso-style-name:"";
	mso-spl-e:yes;}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
.MsoPapDefault
	{mso-style-type:export-only;
	margin-bottom:8.0pt;
	line-height:107%;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-paper-source:0;}
div.WordSection1
	{page:WordSection1;}
-->
</style>
<!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:"Table Normal";
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-priority:99;
	mso-style-parent:"";
	mso-padding-alt:0in 5.4pt 0in 5.4pt;
	mso-para-margin-top:0in;
	mso-para-margin-right:0in;
	mso-para-margin-bottom:8.0pt;
	mso-para-margin-left:0in;
	line-height:107%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
</style>
<![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="1027"/>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext="edit">
  <o:idmap v:ext="edit" data="1"/>
 </o:shapelayout></xml><![endif]-->
</head>

<body lang=EN-US style='tab-interval:.5in'>

<div class=WordSection1>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:
normal'><!--[if gte vml 1]><v:rect id="Rectangle_x0020_1" o:spid="_x0000_s1026"
 style='position:absolute;margin-left:37pt;margin-top:126.25pt;width:540pt;
 height:588.75pt;z-index:251658240;visibility:visible;mso-wrap-style:square;
 mso-width-percent:0;mso-height-percent:0;mso-wrap-distance-left:2.88pt;
 mso-wrap-distance-top:2.88pt;mso-wrap-distance-right:2.88pt;
 mso-wrap-distance-bottom:2.88pt;mso-position-horizontal:absolute;
 mso-position-horizontal-relative:text;mso-position-vertical:absolute;
 mso-position-vertical-relative:text;mso-width-percent:0;mso-height-percent:0;
 mso-width-relative:page;mso-height-relative:page;v-text-anchor:top' o:gfxdata="UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF
90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA
0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD
OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893
SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y
JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl
bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR
JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY
22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i
OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA
IQDEr7+P7AIAABwGAAAOAAAAZHJzL2Uyb0RvYy54bWysVE2P0zAQvSPxHyzfs/lo2rTRpqu22yKk
BVbsIs5u7DQWjh1st9mC+O+Mnaa7hQsCLtF4Mn5+8+bj+uapEejAtOFKFji+ijBislSUy12BPz1u
gilGxhJJiVCSFfjIDL6Zv3513bU5S1StBGUaAYg0edcWuLa2zcPQlDVriLlSLZPws1K6IRaOehdS
TTpAb0SYRNEk7JSmrVYlMwa8t/1PPPf4VcVK+6GqDLNIFBi4Wf/V/rt133B+TfKdJm3NyxMN8hcs
GsIlPHqGuiWWoL3mv0E1vNTKqMpelaoJVVXxkvkcIJs4+iWbh5q0zOcC4pj2LJP5f7Dl+8O9RpxC
7TCSpIESfQTRiNwJhmInT9eaHKIe2nvtEjTtnSq/GCTVqoYottBadTUjFEg5iJPbU388toDnUcIL
GHcwAIi23TtFIYbsrfL6PVW6cc+AMujJl+l4LhN7sqgE52Q6nkYRVLOEf1maZXEydkxDkg/XW23s
G6Ya5IwCa0jJw5PDnbF96BDiXpNqw4XwvSDkhQMwew/zzdTfJjlQAdNFOlK+0N9ncZJGy2QWbCbT
LEg36TiYZdE0iOLZcjaJ0ll6u/nhWMRpXnNKmbzjkg1NF6d/VtRT+/ft4tsOdQVOxikIcsGc5A23
MFuCNwV2ekGAz9AVay2pty3horfDS1peTcjtMsXFZhxl6WgaZNl4FKSjdRQsp5tVsFjFk0m2Xq6W
6/gyxbWXzfx7lp7IUAN3UHvI7qGmHaLc1Xg0niXQgJTDdCdZny8iYgdrqbQaI63sZ25r35iupRyG
XzNsJTQ6EFgQ9Evs3WLfQFv2vpNo4IJF8sIFjXG+7cU68+mle6b6QtmTGs/iAsrQSn5C3FD0I7dV
9AgDAqz9FMCKBaNW+htGHayrApuve6IZRuKthNFzu20w9GBsB4PIEq4W2GLUmyvb78B9q/muBuQ+
cakWMIgV9yPihrRnAXzdAVaQZ35al27HvTz7qOelPv8JAAD//wMAUEsDBBQABgAIAAAAIQBtEZ2X
3wAAAAwBAAAPAAAAZHJzL2Rvd25yZXYueG1sTI/BbsIwEETvlfgHa5F6KzaBtCiNgxCoXKvSXnoz
8TaJGq+DbcDt19c5ldvuzmj2TbmOpmcXdL6zJGE+E8CQaqs7aiR8vL88rID5oEir3hJK+EEP62py
V6pC2yu94eUQGpZCyBdKQhvCUHDu6xaN8jM7ICXtyzqjQlpdw7VT1xRuep4J8ciN6ih9aNWA2xbr
78PZSIgrvbdip3/NZvsa3Wez37mTkfJ+GjfPwALG8G+GET+hQ5WYjvZM2rNewtMyVQkSsjzLgY2G
eT6ejmlaLoQAXpX8tkT1BwAA//8DAFBLAQItABQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAAAAA
AAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhADj9If/WAAAAlAEA
AAsAAAAAAAAAAAAAAAAALwEAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAMSvv4/sAgAAHAYA
AA4AAAAAAAAAAAAAAAAALgIAAGRycy9lMm9Eb2MueG1sUEsBAi0AFAAGAAgAAAAhAG0RnZffAAAA
DAEAAA8AAAAAAAAAAAAAAAAARgUAAGRycy9kb3ducmV2LnhtbFBLBQYAAAAABAAEAPMAAABSBgAA
AAA=
" filled="f" stroked="f" strokeweight="2pt">
 <v:shadow color="black [0]"/>
 <o:lock v:ext="edit" shapetype="t"/>
 <v:textbox inset="0,0,0,0"/>
</v:rect><![endif]--><span style='font-size:12.0pt;font-family:"Times New Roman",serif;
color:windowtext;mso-font-kerning:0pt;mso-ligatures:none;mso-contextual-alternates:
no'><o:p>&nbsp;</o:p></span></p>

<br style='mso-ignore:vglayout' clear=ALL>

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=720
 style='width:7.5in;border-collapse:collapse;mso-yfti-tbllook:1184;mso-padding-alt:
 0in 0in 0in 0in;z-index:1' v:shapes="_x0000_s1028" height=785>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;height:82.7pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:82.7pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>1:30 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:82.7pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>Cross
  acclimation between freezing and drought in herbaceous plants<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Western University<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Ricky Kong &amp; Hugh
  Henry<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>&nbsp;<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1;height:83.5pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:83.5pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>1:45 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:83.5pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>Are
  herbaceous legumes in the northern temperate zone disproportionately
  susceptible to freezing?<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Western University<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Samuel Rycroft &amp; Hugh
  Henry<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2;height:92.1pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:92.1pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>2:00 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:92.1pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>The
  effects of consumer pressure and abiotic stress on plant interactions are
  mediated by extreme climate events<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>University of Alberta<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Alessandro Filazzola,
  Amanda R. Liczner, Michael F. Westphal, Christopher J. Lortie<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3;height:76.25pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:76.25pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>2:15 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:76.25pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>How
  to estimate network structure without data<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><span class=SpellE><i><span
  lang=EN-CA style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Universit</span></i></span><i><span
  lang=EN-CA style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'> de Montral <o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Francis Banville, <span
  class=SpellE>Timothe</span>&nbsp;<span class=SpellE>Poisot</span>, Dominique
  Gravel and Andrew MacDonald<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4;height:110.4pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:110.4pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>2:30 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:110.4pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>The
  influence of climatic drivers on extreme algal outbursts in lakes globally<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>York University<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Arnab Shuvo, Alessandro
  Filazzola, Octavia <span class=SpellE>Mahdiyan</span>, Carolyn <span
  class=SpellE>Ewins</span>, Luke <span class=SpellE>Moslenko</span>, Roberto
  Quinlan, Derek Gray, Catherine OReilly, &amp; Sapna Sharma<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:5;height:64.1pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:64.1pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>2:45 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:64.1pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>Extreme
  events in freshwater lakes in a changing world<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>York University<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Arshad <span class=SpellE>Imrit</span>,
  Alessandro Filazzola, Kevin <span class=SpellE>Blagrave</span>, &amp; Sapna
  Sharma<o:p></o:p></span></i></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:6;mso-yfti-lastrow:yes;height:79.65pt'>
  <td width=122 valign=top style='width:91.15pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:79.65pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><b><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'>3:00 pm</span></span></b><span
  style='mso-armenian-font-family:Verdana;mso-currency-font-family:Verdana;
  mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;mso-greek-font-family:
  Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:Verdana;
  mso-latinext-font-family:Verdana'><i><span lang=EN-CA style='font-size:12.0pt;
  line-height:118%;font-family:"Verdana",sans-serif;mso-ligatures:none;
  mso-ansi-language:EN-CA'><o:p></o:p></span></i></p>
  </td>
  <td width=598 valign=top style='width:448.85pt;padding:2.9pt 2.9pt 2.9pt 2.9pt;
  height:79.65pt'>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><b><span lang=EN-CA style='font-size:12.0pt;line-height:118%;
  font-family:"Verdana",sans-serif;mso-ligatures:none;mso-ansi-language:EN-CA'>Can
  zooplankton on the Great Plains keep up with climate-driven salinity change<o:p></o:p></span></b></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>University of Waterloo<o:p></o:p></span></i></p>
  <p class=MsoNormal style='margin-bottom:1.0pt;mso-pagination:none;tab-stops:
  2.-2283in'><span style='mso-armenian-font-family:Verdana;mso-currency-font-family:
  Verdana;mso-cyrillic-font-family:Verdana;mso-default-font-family:Verdana;
  mso-greek-font-family:Verdana;mso-hebrew-font-family:Verdana;mso-latin-font-family:
  Verdana;mso-latinext-font-family:Verdana'><i><span lang=EN-CA
  style='font-size:12.0pt;line-height:118%;font-family:"Verdana",sans-serif;
  mso-ligatures:none;mso-ansi-language:EN-CA'></span>Mariam <span class=SpellE>Elmarsafy</span>
  &amp; Derek Gray<o:p></o:p></span></i></p>
  </td>
 </tr>
</table>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</div>

</body>

</html>
